services:
    postgres:
        image: postgres
        volumes:
            - .:/postgres
        ports:
            - "5432:5432"
        env_file: ".env.${NODE_ENV}"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5

    rabbitmq:
        image: rabbitmq:management
        volumes:
            - .:/rmq
        ports:
            - "5672:5672"
            - "15672:15672"
        env_file: ".env.${NODE_ENV}"
        healthcheck:
            test: ["CMD-SHELL", "rabbitmqctl status || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 10

    grinder_nest:
        build:
            context: .
            dockerfile: Dockerfile.${NODE_ENV}
        volumes:
            - .:/app
        environment:
            FLASK_DEBUG: "true"
            NODE_ENV: ${NODE_ENV}
        ports:
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy

