apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-service

spec:
    selector:
        app: rabbitmq
    ports:
        -   name: http
            port: 5672

        -   name: admin
            port: 15672
            nodePort: 30001

    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    name: potgres-service

spec:
    selector:
        app: postgres
    ports:
        -   name: http
            port: 5432
            nodePort: 30002
    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    name: grafana-service

spec:
    selector:
        app: grafana
    ports:
        -   name: http
            port: 3000
            nodePort: 30003
    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    name: prom-service

spec:
    selector:
        app: prometheus
    ports:
        -   name: http
            port: 9090
            nodePort: 30004
    type: NodePort
