apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq-deployment
spec:
    selector:
        matchLabels:
            app: rabbitmq
    replicas: 1
    template:
        metadata:
            labels:
                app: rabbitmq
        spec:
            containers:
            - name: rabbitmq
              image: rabbitmq:management
              envFrom:
              -   secretRef:
                      name: tekero-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
spec:
    selector:
        matchLabels:
            app: postgres
    replicas: 1
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
            - name: postgres
              image: postgis/postgis:16-3.5
              envFrom:
              -   secretRef:
                      name: tekero-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana-deployment
spec:
    selector:
        matchLabels:
            app: grafana
    replicas: 1
    template:
        metadata:
            labels:
                app: grafana
        spec:
            containers:
                - name: grafana
                  image: grafana/grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: prom-deployment
spec:
    selector:
        matchLabels:
            app: prometheus
    replicas: 1
    template:
        metadata:
            labels:
                app: prometheus
        spec:
            containers:
                - name: prometheus
                  image: prom/prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekero-deployment
spec:
    selector:
      matchLabels:
        app: tekero-nest
        
