export enum MediaTypesEnum {
  PROFILE_IMAGE = 'PROFILE_IMAGE',
  PROFILE_VIDEO = 'PROFILE_VIDEO',
  MESSAGE_IMAGE = 'MESSAGE_IMAGE',
  MESSAGE_AUDIO = 'MESSAGE_AUDIO',
  MESSAGE_VIDEO = 'MESSAGE_VIDEO'
};
