export enum NotificationTypesEnum {
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  PARTNER_ACCEPTED_INVITATION = 'PARTNER_ACCEPTED_INVITATION',
  LIKE_RECEIVED = 'LIKE_RECEIVED',
  MATCH = 'MATCH',
  PRIVATE_ACCESS_REQUEST = 'PRIVATE_ACCESS_REQUEST',
  LIKES_REFILLED = 'LIKES_REFILLED',
  SYSTEM = 'SYSTEM',
  NOTIFY = 'NOTIFY',
}
