name: Push Docker Image + Terraform infra deploy

on:
    push:
        branches:
            - develop

env:
    IMAGE_NAME: tekero-dev-backend
    AWS_REGION: eu-central-1
    ECR_REGISTRY: 682033469710.dkr.ecr.eu-central-1.amazonaws.com
    CLUSTER_NAME: tekero-dev-ecs-cluster
    SERVICE_NAME: tekero-dev-backend

jobs:
    image-build-and-push:
        name: Build & Push Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              run: |
                  aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

            - name: Build Docker image
              run: |
                  docker build --platform=linux/amd64 -f Dockerfile.production -t $IMAGE_NAME ..

            - name: Tag & Push Docker image
              run: |
                  docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
                  docker push $ECR_REGISTRY/$IMAGE_NAME:latest

    terraform-deploy:
        name: Terraform Apply
        runs-on: ubuntu-latest
        needs: image-build-and-push

        defaults:
            run:
                working-directory: infra

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.5.7

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Terraform Init
              run: terraform init

            - name: Terraform Plan
              run: terraform plan

            - name: Terraform Apply
              run: terraform apply -auto-approve
